title: Nuôi Châu - Phiên bản Giáng Sinh
description: Website tạo ra nhằm mục đích giải trí
baseurl: "/project-nuoi-chau" # để trống nếu dùng domain chaunnm.github.io
url: "https://chaunnm.github.io"
